version: "3"
services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9901:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
    volumes:
      - ./data/config.yml:/etc/kafkaui/dynamic_config.yaml
