version: "3"
services:
  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    image: rabbitmq:3.9.10-management
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
      - ./conf/enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - "5672:5672"
      - "15672:15672"
