# https://github.com/alefiori82/mongo-replica-boilerplate

version: '3'

services:
    mongodb1:
        image: mongo:4
        container_name: mongodb1
        volumes:
        - ./data/mongodata1:/data/db
        expose:
        - "27017"
        ports:
        - "27017:27017"
        entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1"]

    mongodb2:
        image: mongo:4
        container_name: mongodb2
        volumes:
        - ./data/mongodata2:/data/db
        expose:
        - "27017"
        entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1"]
      
    mongodb3:
        image: mongo:4
        container_name: mongodb3
        volumes:
        - ./data/mongodata3:/data/db
        expose:
        - "27017"
        entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1" ]
    
    mongosetup:
        image: "mongo-setup"
        build: "./mongo-setup"
        container_name: "mongosetup"
        depends_on:
            - mongodb1
        volumes:
            - ./data/mongostatus:/data/