version: '3.1'

services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/posgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata