version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis-standalone-data:/data
    ports:
      - "6379:6379"
volumes:
  redis-standalone-data:
    name: redis-standalone-data